name: Check Broken Links

on:
  push:
  schedule:
    - cron: '0 3 * * *'  # Daily at 3 AM 

jobs:
  lychee-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run lychee to check for broken links
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose ./index.html
